lvim.keys.normal_mode["<C-a>"] = "ggVG"
lvim.keys.normal_mode["<M-h>"] = ":BufferLineCyclePrev<CR>"
lvim.keys.normal_mode["<M-l>"] = ":BufferLineCycleNext<CR>"
lvim.keys.normal_mode["<C-s>"] = ":w!<CR>"
lvim.keys.normal_mode["<M-b>"] = ":lua CloseBuffers()<cr>"
lvim.keys.visual_mode["<Tab>"] = "="
