[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "F2", action = "CreateNewWindow" },
  { key = "F3",  mods = "Command", chars = "\u0002%" },
]

[window]
title="Terminal"
dynamic_title=false

dimensions = { columns = 80, lines = 24 }
padding = { x = 4, y = 4 }

[colors.primary]
background = "#080810"
foreground = '#a9b1d6'

[colors.normal]
black=   '#32344a'
red=     '#f7768e'
green=   '#9ece6a'
yellow=  '#e0af68'
blue=    '#7aa2f7'
magenta= '#ad8ee6'
cyan=    '#7dcfff'
white=   '#9699a8'

[colors.bright]
black =  '#444b6a'
red =    '#ff7a93'
green =  '#b9f27c'
yellow = '#ff9e64'
blue =   '#7da6ff'
magenta ='#bb9af7'
cyan =   '#0db9d7'
white =  '#acb0d0'

[font]
size = 9.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"
